root = "/var/local/epm"

[grpc]
  address = "/var/run/containerd/containerd.sock"
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[caches]
  [caches.bundle-cache-pool_occlum_cache0]
    type = "bundle-cache-pool.occlum.cache0"
  [caches.bundle-cache-pool_occlum_cache1]
    type = "bundle-cache-pool.occlum.cache1"
  [caches.bundle-cache-pool_occlum_cache2]
    type = "bundle-cache-pool.occlum.cache2"